package com.redranger00.helloworld.models

data class Hobby (var title : String)

object Supplier {

    val hobbies = listOf(
        Hobby("Reading"),
        Hobby("Writing"),
        Hobby("Fighting"),
        Hobby("Coding"),
        Hobby("Hacking"),
        Hobby("Sleeping"),
        Hobby("Walking"),
        Hobby("Snoring"),
        Hobby("Watching"),
        Hobby("Chatting"),
        Hobby("Breaking"),
        Hobby("Sneezing"),
        Hobby("typing"),
        Hobby("editing"),
        Hobby("photography"),
        Hobby("shooting"),
        Hobby("programming"),
        Hobby("developing"),
        Hobby("making"),
        Hobby("fixing"),
        Hobby("nothing"),
        Hobby("something"),
        Hobby("anything"),
        Hobby("listening"),
        Hobby("ignoring"),
        Hobby("wandering"),
        Hobby("Reading"),
        Hobby("Writing"),
        Hobby("Fighting"),
        Hobby("Coding"),
        Hobby("Hacking"),
        Hobby("Sleeping"),
        Hobby("Walking"),
        Hobby("Snoring"),
        Hobby("Watching"),
        Hobby("Chatting"),
        Hobby("Breaking"),
        Hobby("Sneezing"),
        Hobby("typing"),
        Hobby("editing"),
        Hobby("photography"),
        Hobby("shooting"),
        Hobby("programming"),
        Hobby("developing"),
        Hobby("making"),
        Hobby("fixing"),
        Hobby("nothing"),
        Hobby("something"),
        Hobby("anything"),
        Hobby("listening"),
        Hobby("ignoring"),
        Hobby("wandering")
    )
}